name: Build Lumi APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Show current directory
      run: pwd

    - name: List files in repo root
      run: ls -la ${{ github.workspace }}

    - name: Build APK with Gradle
      run: ./gradlew assembleDebug --stacktrace
      working-directory: ${{ github.workspace }}

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: lumi-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
