name: Сборка Lumi APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить права на Gradle
        run: chmod +x ./gradlew
        working-directory: Lumi

      - name: Сборка APK
        run: ./gradlew assembleDebug --stacktrace
        working-directory: Lumi

      - name: Сохранить APK
        uses: actions/upload-artifact@v2
        with:
          name: Lumi-APK
          path: Lumi/app/build/outputs/apk/debug/app-debug.apk
