name: Build Lumi APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew
        working-directory: Lumi

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: Lumi

      - name: List build outputs
        run: ls -R app/build/outputs/apk/debug
        working-directory: Lumi
