name: Build Lumi APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # без параметра path, чтобы клонировалось в корень /home/runner/work/Lumi

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: ./

    - name: Build debug APK
      run: ./gradlew assembleDebug
      working-directory: ./
