name: Сборка Lumi APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить права на Gradle
        run: chmod +x ./gradlew
        # убрал working-directory, предполагая что gradlew в корне репозитория

      - name: Сборка APK
        run: ./gradlew assembleDebug --stacktrace
        # тоже без working-directory

      - name: Сохранить APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Lumi-APK
          path: app/build/outputs/apk/debug/app-debug.apk
